title: MedLicense.com
default_lang: en
author:
  name: 'Michael Brooks'
  email: mbrooks@medlicense.com
taxonomies:
  - category
  - tag
metadata:
  description: 'Grav is an easy to use, yet powerful, open source flat-file CMS'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
redirects:
  /index.php: /
  /index.html: /
blog:
  route: /blog
